<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Travel>
 */
class TravelFactory extends Factory
{
    private $destinations = [
        "Pozo del Camino (Oeste) | Pozo del Camino (Oeste),  Pozo del Camino",
        "Madrid (Estación Sur) | Calle Mendez Alvaro (Estacion Sur),  Madrid",
        "Montilla  | Calle Conde de La Cortina, 18, Montilla",
        "Aguilar de La Frontera (Córdoba) | Avenida Miguel Cosano, 7, Aguilar",
        "Lucena | Calle de Miguel Cruz Cuenca,  s/n ",
        "Benameji | Carretera Corboba-malaga, 19, Benamejí",
        "Antequera | Paseo de Garcia del Olmo, s/n ",
        "Malaga | Paseo de Los Tilos, s/n ",
        "Torremolinos | Avda.  de Los Manantiales, 29",
        "Fuengirola | Avenida Matias Saez de Tejada,  s/n ",
        "Marbella | Av.  Hermanos Blánquez,  Marbella",
        "Estepona | Avenida del Litoral,  s/n ",
        "La Linea de La Concepcion | Avda.  de Europà,  s/n , La Línea de La Concepción",
        "Algeciras (Puerto) | Puerto de Algeciras,  Algeciras Puerto",
        "Algeciras (Estacion Comes) | Calle San Bernardo, 1 , Algeciras",
        "Madrid Aeropuerto | Avda.  de La Hispanidad s/n ,  Aeropuerto A. Suarez T-4",
        "Murcia | Bº San Andres,  s/n   Estacion de Autobuses",
        "Caravaca de La Cruz | Caravaca",
        "Benidorm | C/ Francisco Llorca Anton, 6  Estacion de Autobuses",
        "Alicante | Muelle Poniente,  s/n   Estación de Autobuses, Est-alican",
        "Elche | Estacion de Autobuses de Elche,  Elche",
        "Mula | Estacion de Autobuses,  Est-mula",
        "Entredicho  | Entredicho,  Cruce-entr",
        "Almaciles | Almaciles-la Codorniz,  Almaciles",
        "Puebla de Don Fadrique | Puebla Don Fadrique,  Pue-don-fa",
        "Venta Chujas | Venta Chujas,  Venta Chujas",
        "Castril | Castril,  Castril",
        "Pozo Alcon | Pozo Alcon,  Pozo Alcon",
        "Quesada | Quesada,  Quesada",
        "Peal de Becerro | Est.  Autobuses Peal,  Est-peal D",
        "Torreperogil | Torreperogil,  Torreperogil",
        "ÚBeda | Estacion de Autobuses de ÚBeda,  ÚBeda",
        "Baeza | Estacion de Autobuses de Baeza,  Baeza",
        "Jaen | Estacion de Autobuses,  Jaen",
        "Huescar | Plaza San Adela,  Huescar",
        "Badajoz | C/ Jose Rebollo Lopez, 2 Estacion de Autobuses",
        "Navalvillar de Pela | Avda.  de La Constitucion,  66, Navalvilla",
        "Huesa | Ctra. A-315,  Km. 3 (Ctra. de Pozo Alcon)",
        "Daimiel | Pza. de La Paz, s/n ",
        "Cartagena | C/ Trovero Marín, s/n   Estación de Autobuses",
        "Tomelloso | Calle Madrid 1,  Tomelloso",
        "Barranda | Bar Candilejas,  Barranda",
        "Ciudad Real | Estacion de Autobuses. Ctra Fuensanta,  s/n ",
        "Pinto | Ctra M-841 (Ramal de Enlace A4-pinto Con M-506) N 10,  Pinto-guardia Civil",
        "Valdemoro | Avda de Andalucía 19,  Av. Andalucía-federico Martín",
        "Seseña | Seseña Nuevo,  Ctra. A4, Ctra.a4-seseña Nuevo",
        "Aranjuez | Pº de Las Infantas, 2",
        "El Romeral | Plaza Mariano García,  El Romeral",
        "Lillo | Calle Ancha 98,  Lillo",
        "Agudo | Pº Juan Xxiii. s/n ,  Agudo",
        "Ajofrin | Pza. Iglesia, s/n (Bar Circulo Recreativo)",
        "Alameda de Cervera | Ctra Alcázar,  Alameda de Cervera",
        "Albaladejo | Calle La Fuente, 19",
        "Alcoba de Los Montes | Ctra. Cm-4106, 4",
        "Alcolea de Calatrava | C/ Cervantes, 68",
        "Alcubillas | C/ Real, 21(n-412)",
        "Algodor | N-400, Km. 13",
        "Argamasilla de Alba | Calle Juan de Zúñiga,  Est. Autobuses Argamasilla de Alba",
        "Arroba de Los Montes | Pl. Constitución, s/n ",
        "Los Ballesteros | Cr-713-c/ Virgen del Rosario,  Los Ballesteros",
        "Burguillos de Toledo | Ctra. Ciudad Real, 34",
        "Cabañas de Yepes | C/ Villafranca de Gaytan, s/n ",
        "Campo de Criptana | C/ Agustin de La Fuente,  Campo de Criptana",
        "Camuñas | Calle Veracruz 24,  Camuñas",
        "Carrion de Calatrava | Calle Real,  Carrion de Calatrava",
        "Las Casas | Plaza Mayor,  Las Casas",
        "Ciruelos | Calle Mayor,  Ciruelos",
        "Consuegra | Avda.  Castilla La Mancha ,  Est.autobuses Consuegra",
        "Los Cortijos (de Abajo) | Avda.  Castilla La Mancha ,  Cortijos de Abajo(los Cortijos)",
        "Los Cortijos (de Arriba) | Avda. Carlos V,  Los Cortijos",
        "El Cristo del Espiritu Santo | Calle Peribañez,  El Cristo del Espiritu Santo",
        "Fernan Caballero | Calle General Herrera, 8",
        "Fontanarejo | Ctra.  Arroba, 27",
        "Fuencaliente(la) | Ctra. del Cristo, 17, La Fuencaliente",
        "Fuenllana | Calle Cervantes, 16",
        "Fuente El Fresno | Travesia Calatrava,  Fuente El Fresno",
        "Herencia | Avenida Alcazar,  Herencia",
        "Horcajo de Los Montes | Crta. de Retuerta, 16 - Bar Mirador",
        "Las Labores | Ctra  Cm-4120 Km 26, 6",
        "Luciana | C/ Piedrabuena, 5-n-430",
        "Madridejos | Paseo del Cristo,  Est. Autobuses Madridejos",
        "Malagon | Ctra Torralba,  Malagón-est. de Autobuses",
        "Montiel | C/ Diputación, 8",
        "Moral de Calatrava | Ctra. Cm-412, 52",
        "Navalpino | C/  Plaza Mayor, ",
        "Puebla del Maestre | Puebla del Maestre",
        "Orgaz | C/ Prado de Lucas, 4",
        "Pedro Muñoz | Avda. Juan Carlos I,  2",
        "Las Peralosas | C/ Belen, 4",
        "Peralvillo | Ctra. N-401 -C/ Peralvillo,  Peralvillo",
        "Picón | Ctra. Cm-412, Km.88",
        "Piedrabuena | C/ Juan de Austria,  Piedrabuena",
        "Porzuna | Ctra. Cm-403,  19",
        "Pozo de La Serna | Ctra. 412,  Km.24",
        "La Puebla de Almoradiel | Calle Prado de La Estación,  La Puebla de Almoradiel",
        "Puebla de Don Rodrigo | C/ Ciudad Real, 28 -Bar Paz",
        "Puerto Lapice | Plaza Constitución 4,  Puerto Lápice",
        "El Robledo | Avda. Independencia, 17",
        "Santa Cruz de La Zarza | Avda.  Castilla La Mancha, ",
        "Santa Cruz de Los Cañamos | Ctra. Cr-6331,  22",
        "Santa Quiteria | Plza. Mayor, s/n ",
        "Sonseca | Avda. Fray Gabriel Magdalena,  Sonseca",
        "El Sotillo | C/ Umbria. 16,  El Sotillo",
        "Tembleque | Avda Andalucía 98,  Tembleque",
        "Terrinches | Plza. de La Libertad, s/n ",
        "Toledo | Avda.  Castilla La Mancha,  s/n ",
        "Torralba de Calatrava | Plza España,  1",
        "Urda | Calle Río Abajo 5,  Urda",
        "Valdemanco de Esteras | C/ Las Escuelas,  2",
        "Valdepeñas | C/ Feria del Vino,  1",
        "Valverde | C/ Valeriano Garcia,  Valverde",
        "Villacañas | Paseo de La Estación,  Villacañas",
        "La Villa de Don Fadrique | Avda de La Constitución 30,  La Villa de Don Fadrique",
        "Villafranca de Los Caballeros | Avda Castilla La Mancha,  Villafranca de Los Caballeros",
        "Villahermosa | Avda.  Castilla La Mancha,  12",
        "Villamuelas | C/ Castilla Con Arenal,  Villamuelas",
        "Villanueva de Bogas | C/ Polideportivo,  4",
        "Villanueva de Los Infantes | Calle Feria,  Villanueva de Los Infantes",
        "Villarrubia de Los Ojos | Calle La Coruña,  Villarrubia de Los Ojos",
        "Villarrubia de Santiago | Ctra. Ocaña,  11",
        "Villasequilla | C/ Fuente,  5",
        "Villatobas | Avda. Mayor del Arrabal, 1",
        "Los Yebenes | Plza. Fuente Nueva, 9",
        "Yepes | Avda de San Luís,  Yepes",
        "Almagro | C/ El Ejido de Calatrava,  s/n ",
        "Fuente del Arco | Fuente del Arco",
        "Dosbarrios | C/ Noblejas, 1",
        "Huerta de Valdecarabanos | C/ Vicenta de Mora, 44",
        "La Guardia | C/ Arrabal, 26",
        "Noblejas | Ctra. Virrarrubia Con Juan Xxiii,  Noblejas",
        "Ocaña | C/ Puertas de Huertas, 7",
        "Valverde de Llerena | Valverde de Llerena",
        "Turleque | Camino de Mora,  Turleque",
        "Alcazar de San Juan | Calle Constitucion (Estacion de Autobuses),  Alcazar de San Juan",
        "Antequera-santa Ana | Carretera Ma-5406 - Estacion Ferrocarril,  s/n , Antequera",
        "Emp.  Archena | Emp. Archen",
        "Casas del Puerto | Casas Puer",
        "Venta Román | Vta Román",
        "Est.  Blanca | Est. Blanca",
        "Campus de Espinardo | C.  Espinar",
        "C. A7/c3223 | C. A7/c3223",
        "Rambla Salada | Ram. Salada",
        "Fortuna | Fortuna",
        "Baln.  Fortuna | Bl. Fortuna",
        "Barinas | Barinas",
        "Pinoso | Pinoso",
        "Emp.  Abarán | Emp. Abarán",
        "Abarán | Abaran",
        "Venta del Olivo | Vta. Olivo",
        "Calasparra | Calasparra",
        "Moratalla | Moratalla",
        "Molina de Segura | Molina Seg",
        "El Palmar | El Palmar. ",
        "Venta La Virgen | V. Virgen Murcia",
        "Venta Malena | Vta Malena",
        "Garcerán | Garcerán",
        "El Albujón | El Albujón",
        "Gimenado | Gimenado",
        "Pozo Estrecho | P. Estrecho",
        "La Palma (Cartagena) | La Palma(cartagena)",
        "La Aparecida (Cartagena) | Cartagena,  Aparecida de Cartagena",
        "Los Beatos | Los Beatos",
        "El Algar | Algar",
        "San Ginés | San Ginés",
        "Los Nietos | Los Nietos",
        "Los Belones | Belones",
        "Cabo de Palos | C. Palos",
        "El Juncal | Juncal Murcia",
        "Aguilas | Estación de Autobuses,  ÁGuilas",
        "Trasierra | Trasierra",
        "Cazadores | Cazadores",
        "Puerto de Mazarrón-Bolnuevo (Playa) | Puerto de Mazarrón/ Bolnuevo",
        "Cañada del Romero | C. Romero",
        "Ventorrillo | Ventorril. ",
        "Cañarico | Cañarico",
        "Sangonera La Verde | Sangonera La Verde",
        "Ramonete | Ramonete",
        "Mazarrón (Pueblo) | Mazarron",
        "Lorca | Lorca",
        "Purias | Purias",
        "Cuesta | Cuesta",
        "Tebar | Tebar",
        "Estrechos | Estrechos",
        "La Escucha | La Escucha",
        "Pulpí | Pulpí",
        "Guazamara | Guazamara",
        "Pto Lumbreras | P. Lumbrera",
        "Almendricos | Almendrico",
        "Velez- Rubio | Velez-rubio",
        "Maria | Maria",
        "Velez-blanco | Velez-blanco",
        "Los Urrutias | Urrutias",
        "Los Alcázares | Alcázares",
        "El Jimenado | El Jimenado",
        "La Unión | Calle Real,  La Unión",
        "Roldán | Roldán",
        "Roda (Región de Murcia) | Roda",
        "Dolores de Pacheco | Dolores",
        "Los Narejos | Narejos",
        "Torre-pacheco | Torre-pacheco",
        "Los Martínez del Puerto | Martínez",
        "Cieza | Estación de Autobuses,  Cieza",
        "Yecla | Yecla",
        "Jumilla | Estación de Autobuses,  Jumilla",
        "La Manga del Mar Menor  | La Manga del Mar Menor",
        "La Campana | Lorca",
        "La Fuente | La Fuente",
        "Pozo Higuera | Pozo Higuera",
        "Ermita El Esparragal | Esparragal",
        "Cuatro Caminos | Cuatro Caminos",
        "Los Pascuales | Los Pascuales",
        "Torrecilla | Torrecilla,  ",
        "Casa Ventanas | Casa Ventanas,  ",
        "Venta Diego | Vta Diego",
        "Venta Petra | Vta Petra",
        "Alburquerque | Avd.  Extremadura,  Alburquerque",
        "Alconchel | Carretera Badajoz S/n,  Alconchel",
        "Almendral | C/  José Segundo Flores,  Almendral",
        "Azuaga | Azuaga,  Azuaga",
        "Barcarrota | C/  Progreso S/n,  Barcarrota",
        "Bodonal de La Sierra | Plaza Blas Marquez,  Bodonal de La Sierra",
        "Cabeza La Vaca | Plaza de España,  Cabeza La Vaca",
        "Calera de Leon | Carretera San Marcos,  Calera de Leon",
        "Campanario | Av.  Constitución,  50-54",
        "Cheles | C/  Moron,  Cheles",
        "Cce C Peni | Ex-107,  Cruce Centro Penitenciario",
        "Cce. S.domi | Ex-107,  Cruce de Santo Domingo",
        "Cce Valuen | N-435,  Cruce de Valuengo",
        "Cce.  S.c.j | Cruce Sagrado Corazon de Jesus,  Cruce Sagrado Corazon de Jesus",
        "Cce. S.rafa | Ex-107,  Cruce San Rafael de Olivenza",
        "Ctel. Botoa | Ex-110,  Cuartel Botoa",
        "Montemolin | Montemolin",
        "Erm. Carrio | Ermita de Carrion,  Ermita de Carrion",
        "Finca Bena | Ex-107,  Finca Benavente",
        "Finca Adel | Ex-107,  Finca La Adelantada",
        "Finca Aren | Ex-107,  Finca Las Arenosas",
        "Finca Cede | Ex-107,  Finca Los Cedeños",
        "Fregenal de La Sierra | Ex-101,  Fregenal de La Sierra",
        "Fuentes de Leon | Ba-092,  Fuentes de Leon",
        "Gevora | C/  Ntra.  Sra. de Guadalupe,  Gevora",
        "Higuera La Real | Calle Colón,  Higuera La Real",
        "Jerez de Los Caballeros | C/  El Rodeo,  Jerez de Los Caballeros",
        "La Albuera | N-432a,  La Albuera",
        "La Codosera | Calle Ramon Y Cajal,  La Codosera",
        "Llerena  | Llerena",
        "Medina de Las Torres | Ba-160,  Medina de Las Torres",
        "Monesterio | Monesterio,  Monesterio",
        "Olivenza | Estacion Autob.  C/  Abelino Palma,  Olivenza",
        "P. Sanchope | ",
        "Puente Zapaton | Ex-110,  Puente de Zapaton",
        "Residencia Lisardo Sanchez | Ex-110,  Residencia Tercera Edad Lisard",
        "Ruecas | Ronda Vegas Altas,  Ruecas",
        "San Benito | C/  Nueva,  San Benito de La Contienda",
        "S. Francisc | San Francisco de Olivenza,  San Francisco de Olivenza",
        "San Vicente de Alcantara | Avd Juan Carlos I,  San Vicente de Alcantara",
        "Segura de Leon | C/  Carretera,  Segura de Leon",
        "Valdebotoa | Valdebotoa,  Valdebotoa",
        "Valencia del Ventoso | Ba-160,  Valencia del Ventoso",
        "Valle de Matamoros | C/  Carretera,  Valle de Matamoros",
        "Valle de Santa Ana | Avd Extremadura,  Valle de Santa Ana",
        "Villanueva del Fresno | Plaza de España,  Villanueva del Fresno",
        "Villar del Rey | C/  San Simon,  Villar del Rey",
        "Zafra | Ctra.  Badajoz-granada,  Zafra",
        "Alajar | Alajar,  Alajar",
        "Aljaraque | Aljaraque,  Aljaraque",
        "Almonaster La Real | Almonaster La Real,  Almonaster La Real",
        "Almonte | Almonte,  Almonte",
        "Alosno | Alosno,  Alosno",
        "Aracena | Aracena,  Aracena",
        "Aroche | Aroche,  Aroche",
        "Ayamonte | Ayamonte,  Ayamonte",
        "Beas | Beas,  Beas",
        "Bellavista | Bellavista,  Bellavista",
        "Berrocal H | Berrocal Huelva,  Berrocal Huelva",
        "Bollullos Par del Condado | Bollullos del Condado,  Bollullos del Condado",
        "Bonares | Bonares,  Bonares",
        "Cabezas Rubias | Cabezas Rubias,  Cabezas Rubias",
        "Calañas | Calañas,  Calañas",
        "Campofrio | Campofrio,  Campofrio",
        "Campus Universitario La Rabida | Campus Univer.   La Rabida,  Campus Univer.  La Rabida",
        "Cartaya | Cartaya,  Cartaya",
        "Cañaveral de Leon | Cañaveral de Leon,  Cañaveral de Leon",
        "Centro Penitenciario de Huelva | Centro Penitenciario Huelva,  Centro Penitenciario Huelva",
        "Chucena | Chucena,  Chucena",
        "Corrales H | Corrales (Huelva),  Corrales (Huelva)",
        "Corteconcepcion | Corteconcepcion,  Corteconcepcion",
        "Cortegana | Cortegana,  Cortegana",
        "Cruce de Isla Cristina | Cruce de  Isla Cristina,  Cruce de  Isla Cristina",
        "Cruce de Aljaraque | Cruce de Aljaraque,  Cruce de Aljaraque",
        "Cce. Arroyo | Cruce de Arroyo,  Cruce de Arroyo",
        "Cce. Berroc | Cruce de Berrocal,  Cruce de Berrocal",
        "Cce. Patras | Cruce de El Patras,  Cruce de El Patras",
        "Cce. Rabida | Cruce de La Rabida,  Cruce de La Rabida",
        "Cce. Moguer | Cruce de Moguer,  Cruce de Moguer",
        "Cce. Refine | Cruce de Refineria,  Cruce de Refineria",
        "Cce. Staana | Cruce de Santa Ana La Real,  Cruce de Santa Ana La Real",
        "Cruce de Villablanca | Cruce de Villablanca,  Cruce de Villablanca",
        "Cruce Ferreira | Cruce Ferreira,  Cruce Ferreira",
        "Cce. Parado | Cruce Parador de Mazagon,  Cruce Parador de Mazagon",
        "Cce. T Loro | Cruce Torre de Loro,  Cruce Torre de Loro",
        "Cumbres de Enmedio | Cumbres de Enmedio,  Cumbres de Enmedio",
        "Cumbres Mayores | Cumbres Mayores,  Cumbres Mayores",
        "Cumbres de San Bartolome | Cumbres San Bartolome,  Cumbres San Bartolome",
        "Almendro | El Almendro,  El Almendro",
        "El Bosque | El Bosque,  El Bosque",
        "El Campillo | El Campillo,  El Campillo",
        "El Cerro de Andevalo | El Cerro de Andevalo,  El Cerro de Andevalo",
        "El Granado | El Granado,  El Granado",
        "El Perruna | El Perrunal,  El Perrunal",
        "El Portil | El Portil,  El Portil",
        "El Repilado | El Repilado,  El Repilado",
        "El Rocio | El Rocio,  El Rocio",
        "El Rompido | El Rompido,  El Rompido",
        "Encinasola | Encinasola,  Encinasola",
        "Escacena | Escacena del Campo,  Escacena del Campo",
        "Est.  Almon | Estacion de Almonaster,  Estacion de Almonaster",
        "Ffcc. Escac | Estacion Ffcc.  Escacena,  Estacion Ffcc. Escacena",
        "Fuenteheridos | Fuenteheridos,  Fuenteheridos",
        "Galaroza | Galaroza,  Galaroza",
        "Gibraleon | Gibraleon,  Gibraleon",
        "Higuera de La Sierra | Higuera de La Sierra,  Higuera de La Sierra",
        "Hinojales | Hinojales,  Hinojales",
        "Hinojos | Hinojos,  Hinojos",
        "Hospital Vazquez Diaz | Hospital Vazquez Diaz,  Hospital Vazquez Diaz",
        "Huelva | Huelva,  Huelva",
        "Islacanela | Isla Canela,  Isla Canela",
        "Isla Cristina | Isla Cristina,  Isla Cristina",
        "Islantilla | Islantilla,  Islantilla",
        "Jabugo | Jabugo,  Jabugo",
        "La Alqueri | La Alqueria,  La Alqueria",
        "La Antilla | La Antilla,  La Antilla",
        "La Bota | La Bota,  La Bota",
        "La Corte | La Corte,  La Corte",
        "La Dehesa | La Dehesa,  La Dehesa",
        "La Granada de Rio Tinto | La Granada de Rio Tinto,  La Granada de Rio Tinto",
        "La Joya(h) | La Joya (Huelva),  La Joya (Huelva)",
        "La Palma del Condado | La Palma del Condado,  La Palma del Condado",
        "La Redondela | La Redondela,  La Redondela",
        "La Zarza | La Zarza,  La Zarza",
        "Lepe | Lepe,  Lepe",
        "Linares de La Sierra | Linares de La Sierra,  Linares de La Sierra",
        "Los Marine | Los Marines,  Los Marines",
        "Los Pinos de Valverde | Los Pinos de Valverde,  Los Pinos de Valverde",
        "Manzanilla | Manzanilla,  Manzanilla",
        "Marigenta | Marigenta,  Marigenta",
        "Marina Punta del Moral | Marina Punta del Moral,  Marina Punta del Moral",
        "Matalascañas | Matalascañas,  Matalascañas",
        "Mazagon | Mazagon,  Mazagon",
        "Membrilloa | Membrillo Alto,  Membrillo Alto",
        "Membrillob | Membrillo Bajo,  Membrillo Bajo",
        "Minas de Riotinto | Minas de Riotinto,  Minas de Riotinto",
        "Moguer | Moguer,  Moguer",
        "Montes de San Benito | Montes de San Benito,  Montes de San Benito",
        "Nerva | Nerva,  Nerva",
        "Niebla | Niebla,  Niebla",
        "N Hospital | Nuevos Hospitales,  Nuevos Hospitales",
        "Palos de La Frontera | Palos de La Frontera,  Palos de La Frontera",
        "Paterna del Campo | Paterna del Campo,  Paterna del Campo",
        "Paymogo | Paymogo,  Paymogo",
        "Peguerilla | Peguerillas,  Peguerillas",
        "Playa Canela | Playa Canela,  Playa Canela",
        "Poblado Mazago | Poblado de Mazagon,  Poblado de Mazagon",
        "Pozo del Camino (Este) | Pozo del Camino (Este),  Pozo del Camino",
        "Puebla de Guzman | Puebla de Guzman,  Puebla de Guzman",
        "Pto Moral | Puerto Moral,  Puerto Moral",
        "Puerto del Moral | Punta del Moral,  Punta del Moral",
        "Punta del Sebo | Punta del Sebo,  Punta del Sebo",
        "Punta Umbria | Punta Umbria,  Punta Umbria",
        "Rociana del Condado | Rociana del Condado,  Rociana del Condado",
        "Rosal de La Frontera | Rosal de La Frontera,  Rosal de La Frontera",
        "San Bartolome de La Torre | San Bartolome de La Torre,  San Bartolome de La Torre",
        "San Juan del Puerto | San Juan del Puerto,  San Juan del Puerto",
        "San Silvestre de Guzman | San Silvestre de Guzman,  San Silvestre de Guzman",
        "San Telmo | San Telmo,  San Telmo",
        "Sanlucar de Guadiana | Sanlucar de Guadiana,  Sanlucar de Guadiana",
        "Santa Ana La Real | Santa Ana La Real,  Santa Ana La Real",
        "Santa Barbara de Casa | Santa Barbara de Casa,  Santa Barbara de Casa",
        "Santa Olalla del Cala | Santa Olalla del Cala,  Santa Olalla del Cala",
        "Sotiel Coronada | Sotiel Coronada,  Sotiel Coronada",
        "Tharsis | Tharsis,  Tharsis",
        "Torrejon | Torrejon,  Torrejon",
        "Trigueros | Trigueros,  Trigueros",
        "Urbasur | Urbasur,  Urbasur",
        "Valdelamusa | Valdelamusa,  Valdelamusa",
        "Valdezufre | Valdezufre,  Valdezufre",
        "Valverde del Camino | Valverde de Camino,  Valverde de Camino",
        "Villablanca | Villablanca,  Villablanca",
        "Villalba del Alcor | Villalba del Alcor,  Villalba del Alcor",
        "Villanueva de Las Cruces | Villanueva de Las Cruces,  Villanueva de Las Cruces",
        "Villanueva de Los Castillejos | Villanueva de Los Castillejos,  Villanueva de Los Castillejos",
        "Villarrasa | Villarrasa,  Villarrasa",
        "Zalamea La Real | Zalamea La Real,  Zalamea La Real",
        "Zufre | Zufre,  Zufre",
        "Almaden de La Plata | Alamaden de La Plata,  Alamaden de La Plata",
        "Alcaladrio | Alcala del Rio,  Alcala del Rio",
        "Aznalcazar | Aznalcazar,  Aznalcazar",
        "Bollullos de La Mitacion | Bollullos de La Mitacion,  Bollullos de La Mitacion",
        "Bormujos | Bormujos,  Bormujos",
        "Burguillos | Burguillos,  Burguillos",
        "Camas | Camas,  Camas",
        "Camposol | Camposol,  Camposol",
        "Castilblanco de Los Arroyos | Castilblanco de Los Arroyos,  Castilblanco de Los Arroyos",
        "Castilleja de La Cuesta | Castilleja de La Cuesta,  Castilleja de La Cuesta",
        "Castilleja del Campo | Castilleja del Campo,  Castilleja del Campo",
        "Castillo de Las Guardas | Castillo de Las Guardas,  Castillo de Las Guardas",
        "El Alamo | El Alamo,  El Alamo",
        "El Garrobo | El Garrobo,  El Garrobo",
        "El Madroño | El Madroño,  El Madroño",
        "El Ronquillo | El Ronquillo,  El Ronquillo",
        "Espartinas | Espartinas,  Espartinas",
        "Gines | Gines,  Gines",
        "La Aulaga | La Aulaga,  La Aulaga",
        "La Rinconada | La Rinconada,  La Rinconada",
        "Las Pajanosas | Las Pajanosas,  Las Pajanosas",
        "Minas del Castillo de Las Guardas | Minas Castillo de Las Guardas,  Minas Castillo de Las Guardas",
        "Nu Sevilla | Nueva Sevilla,  Nueva Sevilla",
        "Pilas | Pilas,  Pilas",
        "Real de La Jara | Real de La Jara,  Real de La Jara",
        "San Ignacio del Viar | San Ignacio del Viar,  San Ignacio del Viar",
        "Sanlucar La Mayor | Sanlucar La Mayor,  Sanlucar La Mayor",
        "Santiponce | Santiponce,  Santiponce",
        "Sevilla (Plaza de Armas) | Sevilla (Plaza de Armas),  Sevilla (Plaza de Armas)",
        "Utrera | Utrera,  Utrera",
        "Valdeflore | Valdeflores,  Valdeflores",
        "Venta La Plata | Venta La Plata,  Venta La Plata",
        "Villamanrique de La Condesa | Villamanrique,  Villamanrique",
        "Villargordo | Villargordo,  Villargordo",
        "Carbonera | Carbonera,  ",
        "Puerto de Mazarrón.  Av. Dr Meca (Sabadell) | Av.  Dr Meca (Sabadell),  ",
        "Condado de Alhama | ",
        "Hacienda del ÁLamo | ",
        "Country Club | ",
        "Bolnuevo | ",
        "Murcia (Aeropuerto/airport) | ",
        "Roda Golf | ",
        "Serena Golf | ",
        "Mar Menor Golf | ",
        "Terrazas Golf | ",
        "La Torre Golf | ",
        "San Pedro del Pinatar | ",
        "Hospital Los Arcos | ",
        "Santiago de La Ribera | Av.  Academia Gral del Aire (Farmacia),  ",
        "San Javier | ",
        "Pallares | Pallares",
        "La Manga (Doblemar,  Sirenas, D´ Costa) | Av.  Gran Vía de La Manga,  ",
        "La Manga Club (Hotel Príncipe Felipe) | ",
        "Lo Pagán | ",
        "Aliseda | C/  Miguel Hernandez,  ",
        "Arroyo de La Luz | C/  Regajal S/n,  ",
        "Cantillana | ",
        "Carbajo | Avd.  Extremadura,  ",
        "Cedillo | C/  Capitan Rojo,  ",
        "El Pino | ",
        "Herrera de Alcantara | ",
        "Herreruela | N-521a,  ",
        "Lapones | ",
        "Las Huertas | ",
        "Malpartida de Caceres | Calle Luis Chamizo,  ",
        "Membrio | Ex-117,  ",
        "Salorino | Calle Dr.  Terron Rodriguez,  ",
        "San Pedro | Cc-107,  ",
        "Santiago de Alcantara | ",
        "Valencia de Alcantara | N-521,  ",
        "Valencia de Alcantara 2 | ",
        "Reina | Reina",
        "Casas de Reina | Casas de Reina",
        "Tarifa | Calle Cruz Roja 2,  Tarifa",
        "Tanger Ville (Bus Y Barco) | Tanger Ville",
        "Tanger Med (Bus Y Barco) | ",
        "Ceuta (Bus Y Barco) | ",
        "Macisvenda | ",
        "Mahoya | ",
        "Abanilla | ",
        "Santomera | ",
        "Abertura | Calle Hernan Cortes,  Abertura",
        "Alcollarin | Ex-102,  Alcollarin",
        "Almoharin | Calle Benavente,  Almoharin",
        "Almorchon | Ex-104,  9",
        "Baterno | Cr-p-4146,  Baterno",
        "Benquerencia de La Serena | Calle Pósito,  18d",
        "Cabeza del Buey | Camino de Campanario,  S/n",
        "Caceres | C\ Túnez,  4",
        "Campolugar | Av.  Constitución,  ",
        "Capilla | Calle Carretera,  47-39",
        "Casas de Don Pedro | C/ Espronceda,  Casas de Don Pedro",
        "Castilblanco | C/  Francisco Naveso,  Castilblanco",
        "Castuera | C\ Zújar 19,  Castuera",
        "Cruce de Acedera | Carretera Orellana,  Cruce de Acedera",
        "Don Benito | Don Benito",
        "El Risco | Ba-130,  10-14",
        "El Torviscal | Av.  Alameda,  El Torviscal",
        "Entrerrios | Plaza España,  Entrerrios",
        "Escurial | Escurial",
        "Esparragosa de Lares | Plaza de España S/n,  Esparragosa de Lares",
        "Fuenlabrada de Los Montes | C/  Canton,  Fuenlabrada de Los Montes",
        "Gargaligas | Ronda del Sur 12,  Gargaligas",
        "Garlitos | Calle Mendoza,  39",
        "Helechal | C/  Carretera S/n,  Helechal",
        "Helechosa de Los Montes | Plaza Las 4 Esquinas,  Helechosa de Los Montes",
        "Hernan Cortes | Ronda America,  Hernan Cortes",
        "Herrera del Duque | Nacional 502,  Herrera del Duque",
        "Higuera de La Serena | C/  Nueva,  Higuera de La Serena",
        "Hospital Don Benito - Villanueva Serena | Avda de Las Vegas Altas,  Don Benito",
        "La Coronada | Calle Luis Chamizo ,  La Coronada",
        "La Nava (Ba) | Calle Cerrillo,  2d, La Nava",
        "Los Guadalperales | Plaza Iglesia,  Guadalperales",
        "Madrigalejo | Plaza de España S/n,  Madrigalejo",
        "Medellin | Ctra de La Estación S/n,  Medellin",
        "Merida | Avda.  de La Libertad, s/n   Estacion de Autobuses",
        "Miajadas | Calle de Los Naranjos S/n,  Miajadas",
        "Monterrubio de La Serena | C/  Corral del Concejo S/n,  Monterrubio de La Serena",
        "Navalvillar de Pela | Avda.  de La Constitucion,  66",
        "Obando | Calle Ronda Pte. ,  1",
        "Orellana de La Sierra | C/  Abelino Palma,  Orellana de La Sierra",
        "Orellana La Vieja | Ctra.  Guadalupe,  Orellana La Vieja",
        "Palazuelo | Rda.  Chopera,  Palazuelo",
        "Pantano de Cijara | Nacional 502,  Pantano de Cijara",
        "Pantano Garcia Sola | Pantano Garcia Sola",
        "Puebla de Alcocer | Avd.  Fco. Chacon 33,  Puebla de Alcocer",
        "Puebla de Alcollarin | Plaza de España S/n,  Puebla de Alcollarin",
        "Peloche | Calle Carretera ,  Peloche",
        "Peñalsordo | Av Juan Carlos I,  Peñalsordo",
        "Pizarro (Cc) | Calle Pacifico,  Pizarro",
        "Puerto de Santa Cruz | Calle Gral.  Franco,  Puerto de Santa Cruz",
        "Quintana de La Serena | Plaza Concordia,  Quintana de La Serena",
        "Rena | Calle Carretera,  Rena",
        "Ruecas | Ronda Vegas Altas,  Ruecas",
        "San Pedro de Merida | Avda de Juan de ÁValos 5,  San Pedro de Merida",
        "Sancti Spiritus | Ba-128,  Sancti Spiritus",
        "Siruela | Plaza de Lagares,  Siruela",
        "Santa Amalia | Avda.  de Valdehornillos S/n,  Santa Amalia",
        "Santa Cruz de La Sierra | Cc.  24, 1",
        "Talarrubias | C\ Fuentecita Ss/n,  Talarrubias",
        "Tamurejo | Ctra.  Ronda de La Siberia,  Tamurejo",
        "Torrefresneda | Avda.  de Las Palmeras S/n,  Torrefresneda",
        "Trujillanos | Paseo de La Hispanidad Nº 1,  Trujillanos",
        "Trujillo | Avd Extremadura,  Trujillo",
        "Valdecaballeros | Carretera Badajoz,  Valdecaballeros",
        "Valdehornillos | C\ Jerte 2,  Valdehornillos",
        "Valdemorales | Carretera 2,  Valdemorales",
        "Valdivia | Calle Ronda Nte,  Valdivia",
        "Valle de La Serena | Ba-113,  Valle de La Serena",
        "Vegas Altas | Calle Ntra.  Sra. del Carmen,  4",
        "Villamesias | Calle Ntra.  Sra. del Carmen,  4",
        "Villar de Rena | Carretera Campolugar,  Villar de Rena",
        "Villarta de Los Montes | Ba-158,  Villarta de Los Montes",
        "Vivares | Avd.  Extremadura.,  Vivares",
        "Villanueva de La Serena  | C\ Hernán Cortés,  1, Villanueva de La Serena",
        "Yelbes | C/ Merinas S/n,  Yelbes",
        "Zarza Capilla | Paseo Máximo Hidalgo 25,  Zarza Capilla",
        "Zorita | Avd.  Constitucion,  Zorita",
        "Zurbaran | Plaza Fuente de Cantos,  Zurbaran",
        "Hospital Talarrubia | Carretera Ex103,  Talarrubias",
        "Cartagena (Bono Upct ) | C/  Trovero Marín s/n  Estación de Autobuses,  Cartagena",
        "Balsicas | ",
        "Pamplona /Iruña.  Estación Bus | Estación Bus.  Yanguas Y Miranda 2,  Pamplona/iruña",
        "San Martín de Unx.  Pl. Miguel Sanz 1 | San Martín de Unx.  Pl. Miguel Sanz 1,  ",
        "San Martín de Unx.  Pl. Miguel Sanz 5 | San Martín de Unx.  Pl. Miguel Sanz 5,  ",
        "Tafalla C/ Recoletas 7 | Tafalla.  C/ Recoletas 7,  ",
        "Tafalla C/ Recoletas 14 | Tafalla.  C/ Recoletas 14,  ",
        "Figarol.  Pl. España 1 | Figarol.  Pl. España 1,  ",
        "Carcastillo.  C/ Aragón F/7 | Carcastillo.  C/ Aragón F/7,  ",
        "Murillo El Fruto.  C/ Mayor 55 | Murillo El Fruto.  C/ Mayor 55,  ",
        "Mélida.  C/ Nueva 14 | Mélida.  C/ Nueva 14,  ",
        "Santacara.  C/ Ctra. Aibar Prox.f/23 | Santacara.  C/ Ctra. Aibar F/17,  ",
        "Santacara.  C/ Ctra. Aibar Prox.23 | Santacara.  C/ Ctra. Aibar Prox.23,  ",
        "Murillo El Cuende.  C/ San Isidro 23 | Murillo El Cuende.  C/ San Isidro 23,  ",
        "Pitillas C/ Beire 5 | Pitillas.  C/ Beire 5,  ",
        "Beire.  Pl. V. Flamarique 1 | Beire.  Pl. V. Flamarique 1,  ",
        "Beire.  C/ Carrera Aragón 6 | Beire.  C/ Carrera Aragón 6,  ",
        "Pueyo.  N-121 Km. 29, 2 A | Pueyo.  N-121 Km. 29, 2 A, ",
        "Garínoain.  C/ Valdorba F/11 | Garínoain.  C/ Valdorba F/11,  ",
        "Barásoain.  C/ Doctor Navarro 10 | Barásoain.  C/ Doctor Navarro 10,  ",
        "Barásoain.  C/ Doctor Navarro F/10 | Barásoain.  C/ Doctor Navarro F/10,  ",
        "Noáin.  C/ Real F/22 | Noáin.  C/ Real F/22,  ",
        "Noáin.  C/ Real 22 | Noáin.  C/ Real 22,  ",
        "Ujué / Uxue.  C/ctra.san Martín F/2 | Ujué / Uxue.  C/ctra.san Martín F/2,  ",
        "Falces.  C/ Fausta Elorz F/3 | Falces.  C/ Fausta Elorz F/3,  ",
        "Miranda de Arga.  Av. San Benito F/14 | Miranda de Arga.  Av. San Benito F/14,  ",
        "Berbinzana.  C/ Nueva 3 (Iglesia) | Berbinzana.  C/ Nueva 3 (Iglesia),  ",
        "Berbinzana.  C/ Nueva 22 | Berbinzana.  C/ Nueva 22,  ",
        "Larraga.  C/ Ctra. Estella 2 | Larraga.  C/ Ctra. Estella 2,  ",
        "Larraga.  C/ Ctra. Berbinzana 2 | Larraga.  C/ Ctra. Berbinzana 2,  ",
        "Marcilla.  Av. Estación 6 | Marcilla.  Av. Estación 6,  ",
        "Tafalla Av.  Baja Navarra F/13 | Tafalla.  Av. Baja Navarra F/13,  ",
        "Tafalla Av.  Baja Navarra 7 | Tafalla.  Av. Baja Navarra 7,  ",
        "Campanas.   Av. Zaragoza F/10 | Campanas.   Av. Zaragoza F/10,  ",
        "Peralta / Azkoien.  C/ Irurzun 24 | Peralta / Azkoien.  C/ Irurzun 24,  ",
        "Peralta / Azkoien.  C/ Irurzun 49 | Peralta / Azkoien.  C/ Irurzun 49,  ",
        "Caparroso.  C/ Ctra. Zaragoza F/10 | Caparroso.  C/ Ctra. Zaragoza F/10,  ",
        "Caparroso.  C/ Ctra. Zaragoza 10 | Caparroso.  C/ Ctra. Zaragoza 10,  ",
        "Artajona.  Av. D.f. Navarra 1 | Artajona.  Av. D.f. Navarra 1,  ",
        "Artajona.  Av. S. Isidro Labrador 2 | Artajona.  Av. S. Isidro Labrador 2,  ",
        "Mendigorría.  C/ Ctra. Larraga F/2 | Mendigorría.  C/ Ctra. Larraga F/2,  ",
        "Peralta / Azkoien.  Av. Funes 4 | Peralta / Azkoien.  Av. Funes 4,  ",
        "Peralta / Azkoien.  Av. Funes 1 | Peralta / Azkoien.  Av. Funes 1,  ",
        "Funes.  Av. Navarra 1 | Funes.  Av. Navarra 1,  ",
        "Funes.  Av. Navarra F/1 | Funes.  Av. Navarra F/1,  ",
        "Marcilla.  Av. Estación 1 | Marcilla.  Av. Estación 1,  ",
        "Pitillas C/ Beire 16 | Pitillas.  C/ Beire 16,  ",
        "Pamplona /Iruña.  Av. Zaragoza Prox. 72 | Pamplona/iruña.  Av. Zaragoza Prox. 72,  ",
        "Larraga.  C/ Ctra. Berbinzana F/56-60 | Larraga.  C/ Ctra. Berbinzana F/56-60,  ",
        "Larraga.  C/ Ctra. Berbinzana 56-60 | Larraga.  C/ Ctra. Berbinzana 56-60,  ",
        "Unzué / Untzue.  C/ Soroeta 2 | Unzué / Untzue.  C/ Soroeta 2,  ",
        "Pamplona /Iruña.  Av. Pio Xii F/41 | Pamplona/iruña.  Av. Pio Xii F/41,  ",
        "Olite / Erriberri.  C/ Rua Romana 8-10 | Olite / Erriberri.  C/ Rua Romana 8-10,  ",
        "Olite / Erriberri.  C/ Alcalde Maillata Prox. 21 | Olite / Erriberri.  C/ Alcalde Maillata Prox. 21,  ",
        "Tiebas.  Camino de Muru 3 | Tiebas.  Camino de Muru 3,  ",
        "Olite / Erriberri.  C/ Rua Romana F/22 | Olite / Erriberri.  C/ Rua Romana F/22,  ",
        "Olite / Erriberri.  C/ Alcalde Maillata 24 | Olite / Erriberri.  C/ Alcalde Maillata 24,  ",
        "Tafalla Intercambiador Bus C/ Pesquera 1 | Tafalla.  Intercambiador Bus. C/ Pesquera 1,  ",
        "Tafalla C/ S.  Martín Unx F/20 (Centro Salud) | Tafalla.  C/ S. Martín Unx F/20 (Centro Salud),  ",
        "Rada.  Av. Navarra 18a | Rada.  Av. Navarra 18a,  ",
        "Murillo El Fruto.  C/ Mayor Prox.64 | Murillo El Fruto.  C/ Mayor Prox.64,  ",
        "Pamplona /Iruña.  C/ Sadar F/6 | Pamplona/iruña.  C/ Sadar F/6,  ",
        "Mendívil.  C/ La Fuente 7 | Mendívil.  C/ La Fuente 7,  ",
        "Mendívil.  C/ La Fuente F/7 | Mendívil.  C/ La Fuente F/7,  ",
        "Garínoain.  C/valdorba 7-9 | Garínoain.  C/valdorba 7-9,  ",
        "Pamplona /Iruña.  F/hospitales. Av. Pio Xii F/34 | Pamplona/iruña.  F/hospitales. Av. Pio Xii F/34,  ",
        "Pamplona /Iruña.  Av.zaragoza F/72 | Pamplona/iruña.  Av.zaragoza F/72,  ",
        "Traibuenas.  C/ Trasera San Juan 23 | Traibuenas.  C/ Trasera San Juan 23,  ",
        "Campanas.  Av.zaragoza 14 | Campanas.  Av.zaragoza 14,  ",
        "Alcala del Valle | Alcala del Valle",
        "Algar | Algar",
        "Algodonales | Algodonales",
        "Aljaima | Aljaima",
        "Almargen | Almargen",
        "Alora | Alora",
        "Arcos de La Frontera | Arcos de La Frontera",
        "Benaocaz | Benaocaz",
        "Benamahoma | Benamahoma",
        "Benaojan | Benaojan",
        "Bornos | Bornos",
        "Cádiz | Cádiz",
        "Cañete La Real | Cañete La Real",
        "Cruce Ardales | Cruce Ardales",
        "Hospital Cartama | Cartama",
        "Carratraca | Carratraca",
        "Costa Ballena | Chipiona",
        "Coto Bornos | Bornos",
        "Cruce Las Cabezas | Las Cabezas de San Juan",
        "Cerralba | Cerralba",
        "Chipiona | Chipiona",
        "Cruce Serrato | Serrato",
        "Cruce Sevilla | ",
        "Cuevas del Becerro | Cuevas del Becerro",
        "Dos Hermanas | Dos Hermanas",
        "Empalme Cañete | Cañete",
        "Estacion Cartama | Cartama",
        "Espera | Espera",
        "Fuengirola-p | Fuengirola",
        "El Gastor | El Gastor",
        "Grazalema | Grazalema",
        "Guadalema | Guadalema de Los Quinteros",
        "Jedula | Jedula",
        "Jerez de La Fra.  | Jerez de La Frontera",
        "Hospital Jerez | Jerez",
        "Las Cabezas S. J. | Las Cabezas de San Juan",
        "Centro Comercial Las Dunas | Sanlúcar de Barrameda",
        "Lebrijah | Lebrija",
        "Lebrija | Lebrija",
        "Las Pajanosas | La Pajanosas",
        "Los Palacios | Los Palacios Y Villafranca",
        "Montecorto | Montecorto",
        "Montejaque | Montejaque",
        "Olvera | Olvera",
        "Centro Penitenciario Pto.  Sta. Maria | Puerto Santa María",
        "Pizarra | Pizarra",
        "Prado del Rey | Prado del Rey",
        "Campus Pto.  Real | Puerto Real",
        "Puerto Real | Puerto Real",
        "Escuela Ingenieria  | Puerto Real",
        "Puerto Sta.  Maria | Puerto Santa Maria",
        "Rec. Ferial | Puerto Santa Maria",
        "Ronda | Ronda",
        "Int. Ronda | Ronda",
        "Rondapor | Ronda",
        "Rota | Rota",
        "Sanlucar de Barrameda | Sanlucar de Barrameda",
        "Setenil | Setenil de Las Bodegas",
        "Sevilla (Prado S. S.) | Sevilla (Prado S. S.),  Sevilla",
        "San Fernando | San Fernando",
        "Sanpedrodeal | San Pedro Alcantara",
        "Torrealhaquime | Torre Alhaquime",
        "El Torbiscal | El Torbiscal",
        "Trebujena | Trebujena",
        "Ubrique | Ubrique",
        "Ventasebastian | Villamartin",
        "Villaluenga | Villaluenga del Rosario",
        "Villamartin | Villamartin",
        "Ardales | Ardales"
    ];

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition()
    {
        $travelDate = $this->faker->dateTimeBetween('+ 1 days', '+ 2 days');
        $stringDate = $travelDate->format('d/m/Y');
        $minutes = [15, 20, 30, 45];
        $starHour = random_int(0, 20);
        $endHour = $starHour + random_int(1, 3);
        $startMinute = $minutes[random_int(0, count($minutes) - 1)];
        $endMinute = $minutes[random_int(0, count($minutes) - 1)];
        return [
            "bus_id" => random_int(1,25),
            "departure_from" => $this->destinations[random_int(0, count($this->destinations)-1)],
            "departure_date" => $stringDate . " " . $starHour . ":" . $startMinute,
            "arrive_to" => $this->destinations[random_int(0, count($this->destinations)-1)],
            "arrive_date" => $stringDate . " " . $endHour . ":" . $endMinute,
        ];            
    }
}
